"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import os
import sys

if (sys.platform == 'darwin') or (sys.platform.startswith('linux')):
    try:
        import py2app
    except:
        pass
else:
    import py2exe

css_dir = 'web/css'
css_files = [os.path.join(css_dir, f)
             for f in os.listdir(css_dir) if os.path.splitext(f)[1] == '.css']
js_dir = 'web/js'
js_files = [os.path.join(js_dir, f)
            for f in os.listdir(js_dir) if os.path.splitext(f)[1] == '.js']
smoothness_dir = 'web/css/smoothness'
smoothness_files = [os.path.join(smoothness_dir, f)
                    for f in os.listdir(smoothness_dir) if os.path.splitext(f)[1] == '.css']
images_dir = 'web/css/smoothness/images'
image_files = [os.path.join(images_dir, f)
               for f in os.listdir(images_dir) if os.path.splitext(f)[1] == '.png']

APP = ['gui.py']
DATA_FILES = [('', ['install-macos.COMMAND', 'export-corpus.COMMAND']),
                ('web', ['web/index_wrapper.html']),
                (css_dir, css_files),
                (js_dir, js_files),
                (smoothness_dir, smoothness_files),
                (images_dir, image_files)]
OPTIONS = {"argv_emulation": True}

setup(
    name='kwaras',
    version='3.0.0rc1',
    install_requires=['openpyxl'],
    setup_requires=['py2exe'],
    packages=['kwaras', 'kwaras.langs', 'kwaras.conf', 'kwaras.formats', 'kwaras.process'],
    package_dir={'kwaras': '',
                 'kwaras.langs': 'kwaras/langs', 'kwaras.conf': 'kwaras/conf',
                 'kwaras.formats': 'kwaras/formats', 'kwaras.process': 'kwaras/process'},
    url='http://github.com/ucsd-field-lab/kwaras',
    license='MIT-LICENSE',
    author='Lucien Carroll',
    author_email='lucien@discurs.us',
    description='Tools for managing ELAN corpus files',
    console=['gui.py'],
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)
